import { PostProps } from "./post";
import { Tab as TabProps } from "./tab";
import { Icon as IconProps } from "./icon";
import { Input as InputProps } from "./input";
import { ProfileTabsProps } from "./profileTab";
import { MostPopularProps } from "./mostPopular";
import { TopCategoriesProps } from "./topCategory";
import { TextArea as TextAreaProps } from "./textArea";
import { TitleWithIcon as TWIconProps } from "./titleWithIcon";
import { FontAwesomeIcon as FAIconProps } from "./fontAwesomeIcon";

export type { TabProps };
export type { PostProps };
export type { IconProps };
export type { InputProps };
export type { FAIconProps };
export type { TWIconProps };
export type { TextAreaProps };
export type { ProfileTabsProps };
export type { MostPopularProps };
export type { TopCategoriesProps };
