import { PostProps } from "./post";
import { CommentProps } from "./comment";
import { Icon as IconProps } from "./icon";
import { AuthorCardProps } from "./authorData";
import { FeaturedProps } from "./featuredPost";
import { MostPopularProps } from "./mostPopular";
import { TopCategoriesProps } from "./topCategory";
import { TextArea as TextAreaProps } from "./textArea";
import { FeaturedWritersProps } from "./featuredWriter";
import { TitleWithIcon as TWIconProps } from "./titleWithIcon";

export type { PostProps };
export type { IconProps };
export type { TWIconProps };
export type { CommentProps };
export type { TextAreaProps };
export type { FeaturedProps };
export type { AuthorCardProps };
export type { MostPopularProps };
export type { TopCategoriesProps };
export type { FeaturedWritersProps };
